language: go

go:
#  - 1.0 This won't work with coveralls
#  - 1.1 This won't work with coveralls
#  - 1.2 This won't work with our XML wonderfulness
  - 1.3
  - 1.4
  - tip

before_install:
  - go get -u github.com/axw/gocov/gocov
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/golang/lint

script:
  - .ci_helpers/format.sh
  - go test -v -race -covermode=count -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
